Repository TRIP-Side-Project/backend, pull requests merged in 2023-12, with the labels that each got.

#6 로그인 및 회원가입 기능 구현(JWT)
  build.gradle
  src/main/java/com/api/trip/common/security/JwtToken.java
  src/main/java/com/api/trip/common/security/JwtTokenFilter.java
  src/main/java/com/api/trip/common/security/JwtTokenProvider.java
  src/main/java/com/api/trip/common/security/MemberSecurityService.java
  src/main/java/com/api/trip/common/security/SecurityConfig.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/JoinRequest.java
  src/main/java/com/api/trip/domain/member/controller/dto/LoginRequest.java
  src/main/java/com/api/trip/domain/member/controller/dto/LoginResponse.java
  src/main/java/com/api/trip/domain/member/model/Member.java
  src/main/java/com/api/trip/domain/member/repository/MemberRepository.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: 🚀 Feat

#15 JWT 코드 리팩토링
  src/main/java/com/api/trip/common/security/JwtToken.java
  src/main/java/com/api/trip/common/security/JwtTokenFilter.java
  src/main/java/com/api/trip/common/security/JwtTokenProvider.java
  src/main/java/com/api/trip/common/security/MemberSecurityService.java
  src/main/java/com/api/trip/common/security/SecurityConfig.java
  src/main/java/com/api/trip/common/security/dto/AuthenticationMember.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/model/Member.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
  src/main/resources/application.yml
Labels: ♻️ Refactor

#18 Swagger 적용
  build.gradle
  src/main/java/com/api/trip/common/security/SecurityConfig.java
Labels: 🚀 Feat, Chore

#19 jwt 로그인 기능 리팩토링 + Swagger UI 추가
  build.gradle
  src/main/java/com/api/trip/common/security/JwtToken.java
  src/main/java/com/api/trip/common/security/JwtTokenFilter.java
  src/main/java/com/api/trip/common/security/JwtTokenProvider.java
  src/main/java/com/api/trip/common/security/MemberSecurityService.java
  src/main/java/com/api/trip/common/security/SecurityConfig.java
  src/main/java/com/api/trip/common/security/dto/AuthenticationMember.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/model/Member.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
  src/main/resources/application.yml
Labels: 🚀 Feat, ♻️ Refactor, Chore

#23 이메일 인증 기능 구현
  build.gradle
  src/main/java/com/api/trip/common/security/JwtTokenFilter.java
  src/main/java/com/api/trip/domain/email/model/EmailAuth.java
  src/main/java/com/api/trip/domain/email/repository/EmailAuthRepository.java
  src/main/java/com/api/trip/domain/email/repository/EmailAuthRepositoryCustom.java
  src/main/java/com/api/trip/domain/email/repository/EmailAuthRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/EmailResponse.java
  src/main/java/com/api/trip/domain/member/controller/dto/JoinRequest.java
  src/main/java/com/api/trip/domain/member/model/Member.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
  src/main/resources/application.yml
Labels: 🚀 Feat, ♻️ Refactor, Docs

#26 JPA Auditing 적용
  src/main/java/com/api/trip/common/auditing/config/AuditingConfig.java
  src/main/java/com/api/trip/common/auditing/entity/BaseTimeEntity.java
  src/main/java/com/api/trip/domain/email/model/EmailAuth.java
  src/main/java/com/api/trip/domain/member/model/Member.java
Labels: Feat

#29 댓글 기능 구현
  src/main/java/com/api/trip/domain/comment/controller/CommentController.java
  src/main/java/com/api/trip/domain/comment/controller/dto/CommentResponse.java
  src/main/java/com/api/trip/domain/comment/controller/dto/CreateCommentRequest.java
  src/main/java/com/api/trip/domain/comment/controller/dto/UpdateCommentRequest.java
  src/main/java/com/api/trip/domain/comment/model/Comment.java
  src/main/java/com/api/trip/domain/comment/repository/CommentRepository.java
  src/main/java/com/api/trip/domain/comment/repository/CommentRepositoryCustom.java
  src/main/java/com/api/trip/domain/comment/repository/CommentRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/comment/service/CommentService.java
Labels: Feat

#33 회원 탈퇴 기능 구현
  src/main/java/com/api/trip/common/auditing/entity/BaseTimeEntity.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/DeleteRequest.java
  src/main/java/com/api/trip/domain/member/model/Member.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
  src/test/java/com/api/trip/domain/member/controller/MemberControllerTest.java
  src/test/java/com/api/trip/domain/member/service/MemberServiceTest.java
Labels: Feat, Test

#31 게시판 관련 코드 리팩토링
  src/main/java/com/api/trip/domain/article/controller/ArticleController.java
  src/main/java/com/api/trip/domain/article/controller/dto/CreateArticleRequest.java
  src/main/java/com/api/trip/domain/article/controller/dto/GetArticlesResponse.java
  src/main/java/com/api/trip/domain/article/controller/dto/GetMyArticlesResponse.java
  src/main/java/com/api/trip/domain/article/controller/dto/ReadArticleResponse.java
  src/main/java/com/api/trip/domain/article/model/Article.java
  src/main/java/com/api/trip/domain/article/repository/ArticleRepositoryCustom.java
  src/main/java/com/api/trip/domain/article/service/ArticleService.java
  src/main/java/com/api/trip/domain/comment/controller/CommentController.java
  src/main/java/com/api/trip/domain/comment/controller/dto/CommentResponse.java
  src/main/java/com/api/trip/domain/comment/controller/dto/CreateCommentRequest.java
  src/main/java/com/api/trip/domain/comment/controller/dto/GetCommentsResponse.java
  src/main/java/com/api/trip/domain/comment/controller/dto/GetMyCommentsResponse.java
  src/main/java/com/api/trip/domain/comment/model/Comment.java
  src/main/java/com/api/trip/domain/comment/service/CommentService.java
  src/main/resources/application.yml
Labels: Refactor

#38 코드 리팩토링 & 변경 사항 반영
  src/main/java/com/api/trip/common/auditing/config/AuditingConfig.java
  src/main/java/com/api/trip/common/security/config/SecurityConfig.java
  src/main/java/com/api/trip/common/security/jwt/JwtToken.java
  src/main/java/com/api/trip/common/security/jwt/JwtTokenFilter.java
  src/main/java/com/api/trip/common/security/jwt/JwtTokenProvider.java
  src/main/java/com/api/trip/common/security/service/MemberSecurityService.java
  src/main/java/com/api/trip/common/security/util/SecurityUtils.java
  src/main/java/com/api/trip/domain/article/controller/ArticleController.java
  src/main/java/com/api/trip/domain/article/model/Article.java
  src/main/java/com/api/trip/domain/article/service/ArticleService.java
  src/main/java/com/api/trip/domain/comment/controller/CommentController.java
  src/main/java/com/api/trip/domain/comment/model/Comment.java
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/JoinRequest.java
  src/main/java/com/api/trip/domain/member/controller/dto/LoginResponse.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
  src/test/java/com/api/trip/TripApplicationTests.java
  src/test/java/com/api/trip/domain/member/controller/MemberControllerTest.java
  src/test/java/com/api/trip/domain/member/service/MemberServiceTest.java
Labels: Refactor

#42 프로필 이미지 업로드 기능 구현
  build.gradle
  src/main/java/com/api/trip/domain/aws/config/AmazonS3Config.java
  src/main/java/com/api/trip/domain/aws/service/AmazonS3Service.java
  src/main/java/com/api/trip/domain/aws/util/MultipartFileUtils.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/model/Member.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
  src/main/resources/application.yml
Labels: Feat

#40 여행 상품 기능 구현(정렬 부분X)
  src/main/java/com/api/trip/domain/item/controller/ItemController.java
  src/main/java/com/api/trip/domain/item/controller/dto/CreateItemRequest.java
  src/main/java/com/api/trip/domain/item/controller/dto/GetItemResponse.java
  src/main/java/com/api/trip/domain/item/controller/dto/GetItemsResponse.java
  src/main/java/com/api/trip/domain/item/model/Item.java
  src/main/java/com/api/trip/domain/item/repository/ItemRepository.java
  src/main/java/com/api/trip/domain/item/repository/ItemRepositoryCustom.java
  src/main/java/com/api/trip/domain/item/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/item/service/ItemService.java
Labels: Feat

#43 관심상품 기능 구현
  src/main/java/com/api/trip/domain/interestitem/InterestItem.java
  src/main/java/com/api/trip/domain/interestitem/controller/InterestItemController.java
  src/main/java/com/api/trip/domain/interestitem/controller/dto/CreateInterestItemRequest.java
  src/main/java/com/api/trip/domain/interestitem/controller/dto/GetInterestItemsResponse.java
  src/main/java/com/api/trip/domain/interestitem/repository/InterestItemRepository.java
  src/main/java/com/api/trip/domain/interestitem/service/InterestItemService.java
  src/main/java/com/api/trip/domain/item/controller/ItemController.java
  src/main/java/com/api/trip/domain/item/service/ItemService.java
Labels: Feat

#44 게시글 좋아요 기능 구현
  src/main/java/com/api/trip/domain/article/controller/ArticleController.java
  src/main/java/com/api/trip/domain/article/controller/dto/GetArticlesResponse.java
  src/main/java/com/api/trip/domain/article/controller/dto/ReadArticleResponse.java
  src/main/java/com/api/trip/domain/article/model/Article.java
  src/main/java/com/api/trip/domain/article/repository/ArticleRepository.java
  src/main/java/com/api/trip/domain/article/repository/ArticleRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/article/service/ArticleService.java
  src/main/java/com/api/trip/domain/comment/controller/dto/GetCommentsResponse.java
  src/main/java/com/api/trip/domain/interestarticle/controller/InterestArticleController.java
  src/main/java/com/api/trip/domain/interestarticle/controller/dto/CreateInterestArticleRequest.java
  src/main/java/com/api/trip/domain/interestarticle/model/InterestArticle.java
  src/main/java/com/api/trip/domain/interestarticle/repository/InterestArticleRepository.java
  src/main/java/com/api/trip/domain/interestarticle/service/InterestArticleService.java
Labels: BugFix, Feat, Refactor

#47 CORS TEST
  src/main/java/com/api/trip/common/WebConfig.java
Labels: Test

#51 소셜 로그인 기능 설계 (구현 X)
  build.gradle
  src/main/java/com/api/trip/common/security/config/SecurityConfig.java
  src/main/java/com/api/trip/common/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/api/trip/common/security/oauth/OAuth2Attribute.java
  src/main/java/com/api/trip/common/security/oauth/OAuthFailureHandler.java
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
Labels: Feat, Setting

#52 비밀번호 변경 기능 구현
  src/main/java/com/api/trip/common/security/config/SecurityConfig.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/UpdatePasswordRequest.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat

#53 Merge Pull Request to dev
  build.gradle
  src/main/java/com/api/trip/common/security/config/SecurityConfig.java
  src/main/java/com/api/trip/common/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/api/trip/common/security/oauth/OAuth2Attribute.java
  src/main/java/com/api/trip/common/security/oauth/OAuthFailureHandler.java
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/UpdatePasswordRequest.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat

#57 좋아요 수 컬럼 추가 및 검색 정렬 기능 추가
  src/main/java/com/api/trip/domain/interestitem/service/InterestItemService.java
  src/main/java/com/api/trip/domain/item/controller/ItemController.java
  src/main/java/com/api/trip/domain/item/model/Item.java
  src/main/java/com/api/trip/domain/item/repository/ItemRepository.java
  src/main/java/com/api/trip/domain/item/repository/ItemRepositoryCustom.java
  src/main/java/com/api/trip/domain/item/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/item/service/ItemService.java
Labels: Feat

#59 게시글 목록 조회 API 변경
  src/main/java/com/api/trip/common/WebConfig.java
  src/main/java/com/api/trip/domain/article/controller/dto/GetArticlesResponse.java
Labels: BugFix, Feat

#60 게시글 목록 조회 API 변경
  src/main/java/com/api/trip/common/WebConfig.java
  src/main/java/com/api/trip/domain/article/controller/dto/GetArticlesResponse.java
  src/main/java/com/api/trip/domain/interestitem/service/InterestItemService.java
  src/main/java/com/api/trip/domain/item/controller/ItemController.java
  src/main/java/com/api/trip/domain/item/model/Item.java
  src/main/java/com/api/trip/domain/item/repository/ItemRepository.java
  src/main/java/com/api/trip/domain/item/repository/ItemRepositoryCustom.java
  src/main/java/com/api/trip/domain/item/repository/ItemRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/item/service/ItemService.java
Labels: BugFix, Feat

#61 [리팩토링] 이메일 인증 기능
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/EmailResponse.java
Labels: Feat

#62 [리팩토링] 이메일 인증 기능
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/EmailResponse.java
Labels: Feat

#66 swagger에서 http로 요청하는 이슈 해결
  src/main/java/com/api/trip/common/SwaggerConfig.java
Labels: BugFix

#67 swagger에서 http로 요청하는 이슈 해결
  src/main/java/com/api/trip/common/SwaggerConfig.java
Labels: BugFix

#68 회원 가입 기능 수정
  src/main/java/com/api/trip/domain/email/repository/EmailAuthRepository.java
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: BugFix

#69 회원 가입 로직 버그 수정
  src/main/java/com/api/trip/domain/email/repository/EmailAuthRepository.java
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: BugFix

#71 회원 가입 기능 수정
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/JoinRequest.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: BugFix

#72 회원 가입 로직 수정 merge
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/JoinRequest.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: BugFix

#74 swagger 전역에 accessToken 헤더 추가
  src/main/java/com/api/trip/common/SwaggerConfig.java
Labels: Feat

#75 swagger 전역에 accessToken 헤더 추가
  src/main/java/com/api/trip/common/SwaggerConfig.java
Labels: Feat

#76 태그 기능 구현
  src/main/java/com/api/trip/domain/interestitem/controller/dto/CreateInterestItemRequest.java
  src/main/java/com/api/trip/domain/interestitem/controller/dto/GetInterestItemsResponse.java
  src/main/java/com/api/trip/domain/interestitem/model/InterestItem.java
  src/main/java/com/api/trip/domain/interestitem/repository/InterestItemRepository.java
  src/main/java/com/api/trip/domain/interestitem/service/InterestItemService.java
  src/main/java/com/api/trip/domain/item/controller/ItemController.java
  src/main/java/com/api/trip/domain/item/controller/dto/CreateItemRequest.java
  src/main/java/com/api/trip/domain/item/service/ItemService.java
  src/main/java/com/api/trip/domain/itemtag/model/ItemTag.java
  src/main/java/com/api/trip/domain/itemtag/repository/ItemTagRepository.java
  src/main/java/com/api/trip/domain/itemtag/repository/ItemTagRepositoryCustom.java
  src/main/java/com/api/trip/domain/itemtag/repository/ItemTagRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/itemtag/service/ItemTagService.java
  src/main/java/com/api/trip/domain/tag/model/Tag.java
  src/main/java/com/api/trip/domain/tag/repository/TagRepository.java
  src/main/java/com/api/trip/domain/tag/service/TagService.java
Labels: Feat

#78 소셜 로그인 기능 구현
  src/main/java/com/api/trip/common/security/config/SecurityConfig.java
  src/main/java/com/api/trip/common/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/api/trip/common/security/oauth/OAuth2Attribute.java
  src/main/java/com/api/trip/common/security/oauth/OAuthFailureHandler.java
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
Labels: Feat

#79 태그 & 소셜 로그인 기능 구현
  src/main/java/com/api/trip/common/security/config/SecurityConfig.java
  src/main/java/com/api/trip/common/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/api/trip/common/security/oauth/OAuth2Attribute.java
  src/main/java/com/api/trip/common/security/oauth/OAuthFailureHandler.java
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/trip/domain/interestitem/controller/dto/CreateInterestItemRequest.java
  src/main/java/com/api/trip/domain/interestitem/controller/dto/GetInterestItemsResponse.java
  src/main/java/com/api/trip/domain/interestitem/model/InterestItem.java
  src/main/java/com/api/trip/domain/interestitem/repository/InterestItemRepository.java
  src/main/java/com/api/trip/domain/interestitem/service/InterestItemService.java
  src/main/java/com/api/trip/domain/item/controller/ItemController.java
  src/main/java/com/api/trip/domain/item/controller/dto/CreateItemRequest.java
  src/main/java/com/api/trip/domain/item/service/ItemService.java
  src/main/java/com/api/trip/domain/itemtag/model/ItemTag.java
  src/main/java/com/api/trip/domain/itemtag/repository/ItemTagRepository.java
  src/main/java/com/api/trip/domain/itemtag/repository/ItemTagRepositoryCustom.java
  src/main/java/com/api/trip/domain/itemtag/repository/ItemTagRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/itemtag/service/ItemTagService.java
  src/main/java/com/api/trip/domain/tag/model/Tag.java
  src/main/java/com/api/trip/domain/tag/repository/TagRepository.java
  src/main/java/com/api/trip/domain/tag/service/TagService.java
Labels: Feat

#80 예외 전역 처리 구조 세팅
  src/main/java/com/api/trip/common/exception/CustomException.java
  src/main/java/com/api/trip/common/exception/ErrorCode.java
  src/main/java/com/api/trip/common/exception/ErrorResponse.java
  src/main/java/com/api/trip/common/exception/GlobalExceptionHandler.java
  src/main/java/com/api/trip/common/exception/custom_exception/NotFoundException.java
Labels: Feat

#81 예외 구조 세팅
  src/main/java/com/api/trip/common/exception/CustomException.java
  src/main/java/com/api/trip/common/exception/ErrorCode.java
  src/main/java/com/api/trip/common/exception/ErrorResponse.java
  src/main/java/com/api/trip/common/exception/GlobalExceptionHandler.java
  src/main/java/com/api/trip/common/exception/custom_exception/NotFoundException.java
Labels: Feat

#82 게시글 파일(이미지) 업로드 기능 구현
  src/main/java/com/api/trip/domain/article/model/Article.java
  src/main/java/com/api/trip/domain/article/service/ArticleService.java
  src/main/java/com/api/trip/domain/article/util/UrlExtractor.java
  src/main/java/com/api/trip/domain/articlefile/controller/ArticleFileController.java
  src/main/java/com/api/trip/domain/articlefile/model/ArticleFile.java
  src/main/java/com/api/trip/domain/articlefile/repository/ArticleFileRepository.java
  src/main/java/com/api/trip/domain/articlefile/scheduler/ArticleFileScheduler.java
  src/main/java/com/api/trip/domain/articlefile/service/ArticleFileService.java
  src/main/java/com/api/trip/domain/articlefile/uploader/ArticleFileUploader.java
Labels: Feat

#84 소셜 로그인 수정
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
Labels: Feat

#85 Main Merge
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/trip/domain/article/model/Article.java
  src/main/java/com/api/trip/domain/article/service/ArticleService.java
  src/main/java/com/api/trip/domain/article/util/UrlExtractor.java
  src/main/java/com/api/trip/domain/articlefile/controller/ArticleFileController.java
  src/main/java/com/api/trip/domain/articlefile/model/ArticleFile.java
  src/main/java/com/api/trip/domain/articlefile/repository/ArticleFileRepository.java
  src/main/java/com/api/trip/domain/articlefile/scheduler/ArticleFileScheduler.java
  src/main/java/com/api/trip/domain/articlefile/service/ArticleFileService.java
  src/main/java/com/api/trip/domain/articlefile/uploader/ArticleFileUploader.java
Labels: Feat

#88 Redis 기본 설정
  build.gradle
  src/main/java/com/api/trip/common/redis/EmbeddedRedisConfig.java
  src/main/java/com/api/trip/common/redis/RedisConfig.java
  src/main/java/com/api/trip/common/redis/RedisService.java
  src/main/resources/application.yml
Labels: Setting

#91 embeddedRedis 제거
  src/main/java/com/api/trip/common/redis/EmbeddedRedisConfig.java
  src/main/java/com/api/trip/common/redis/RedisConfig.java
  src/main/resources/application.yml
Labels: Remove

#92 Redis 설정 추가
  build.gradle
  src/main/java/com/api/trip/common/redis/RedisConfig.java
  src/main/java/com/api/trip/common/redis/RedisService.java
  src/main/resources/application.yml
Labels: Feat

#94 게시글 관련 기능 추가 및 수정
  src/main/java/com/api/trip/domain/article/controller/ArticleController.java
  src/main/java/com/api/trip/domain/article/controller/dto/CreateArticleRequest.java
  src/main/java/com/api/trip/domain/article/controller/dto/ReadArticleResponse.java
  src/main/java/com/api/trip/domain/article/controller/dto/UpdateArticleRequest.java
  src/main/java/com/api/trip/domain/article/repository/ArticleRepositoryCustom.java
  src/main/java/com/api/trip/domain/article/repository/ArticleRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/article/service/ArticleService.java
  src/main/java/com/api/trip/domain/articletag/model/ArticleTag.java
  src/main/java/com/api/trip/domain/articletag/repository/ArticleTagRepository.java
  src/main/java/com/api/trip/domain/articletag/repository/ArticleTagRepositoryCustom.java
  src/main/java/com/api/trip/domain/articletag/repository/ArticleTagRepositoryCustomImpl.java
Labels: Feat

#93 refreshToken도입 + 로그아웃 기능 구현
  src/main/java/com/api/trip/common/exception/ErrorCode.java
  src/main/java/com/api/trip/common/exception/custom_exception/BadRequestException.java
  src/main/java/com/api/trip/common/exception/custom_exception/InvalidException.java
  src/main/java/com/api/trip/common/security/jwt/JwtTokenFilter.java
  src/main/java/com/api/trip/common/security/jwt/JwtTokenProvider.java
  src/main/java/com/api/trip/common/security/util/JwtTokenUtils.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat

#100 상품 도메인 리팩토링(태그 검색, imageUrl추가)
  src/main/java/com/api/trip/domain/item/controller/ItemController.java
  src/main/java/com/api/trip/domain/item/controller/dto/CreateItemRequest.java
  src/main/java/com/api/trip/domain/item/controller/dto/GetItemsResponse.java
  src/main/java/com/api/trip/domain/item/model/Item.java
  src/main/java/com/api/trip/domain/item/service/ItemService.java
  src/main/java/com/api/trip/domain/itemtag/repository/ItemTagRepositoryCustom.java
  src/main/java/com/api/trip/domain/itemtag/repository/ItemTagRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/itemtag/service/ItemTagService.java
  src/main/java/com/api/trip/domain/tag/repository/TagRepository.java
  src/main/java/com/api/trip/domain/tag/service/TagService.java
Labels: Feat, Refactor

#103 관심상품 response 수정
  src/main/java/com/api/trip/domain/interestitem/controller/dto/GetInterestItemsResponse.java
Labels: BugFix

#105 소셜 로그인 기능 수정
  src/main/java/com/api/trip/common/exception/ErrorCode.java
  src/main/java/com/api/trip/common/security/oauth/OAuth2Attribute.java
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
Labels: BugFix

#106 회원 유효성 검사 & 예외 처리
  src/main/java/com/api/trip/common/exception/ErrorCode.java
  src/main/java/com/api/trip/common/exception/custom_exception/DuplicateException.java
  src/main/java/com/api/trip/common/exception/custom_exception/NotMatchException.java
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/JoinRequest.java
  src/main/java/com/api/trip/domain/member/controller/dto/LoginRequest.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat

#108 상품 유효성 검증 및 예외처리
  src/main/java/com/api/trip/common/exception/ErrorCode.java
  src/main/java/com/api/trip/common/exception/custom_exception/ForbiddenException.java
  src/main/java/com/api/trip/domain/item/controller/ItemController.java
  src/main/java/com/api/trip/domain/item/controller/dto/CreateItemRequest.java
  src/main/java/com/api/trip/domain/item/model/Item.java
  src/main/java/com/api/trip/domain/item/service/ItemService.java
Labels: Feat

#109 게시판 관련 예외 처리
  src/main/java/com/api/trip/common/exception/CustomException.java
  src/main/java/com/api/trip/common/exception/ErrorCode.java
  src/main/java/com/api/trip/domain/article/controller/dto/CreateArticleRequest.java
  src/main/java/com/api/trip/domain/article/service/ArticleService.java
  src/main/java/com/api/trip/domain/articlefile/service/ArticleFileService.java
  src/main/java/com/api/trip/domain/articlefile/uploader/ArticleFileUploader.java
  src/main/java/com/api/trip/domain/comment/controller/dto/CreateCommentRequest.java
  src/main/java/com/api/trip/domain/comment/service/CommentService.java
  src/main/java/com/api/trip/domain/interestarticle/controller/dto/CreateInterestArticleRequest.java
  src/main/java/com/api/trip/domain/interestarticle/repository/InterestArticleRepository.java
  src/main/java/com/api/trip/domain/interestarticle/service/InterestArticleService.java
Labels: Feat

#111 merge main
  build.gradle
  src/main/java/com/api/trip/common/exception/CustomException.java
  src/main/java/com/api/trip/common/exception/ErrorCode.java
  src/main/java/com/api/trip/common/exception/custom_exception/DuplicateException.java
  src/main/java/com/api/trip/common/exception/custom_exception/ForbiddenException.java
  src/main/java/com/api/trip/common/exception/custom_exception/NotMatchException.java
  src/main/java/com/api/trip/common/security/oauth/OAuth2Attribute.java
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/trip/domain/article/controller/dto/CreateArticleRequest.java
  src/main/java/com/api/trip/domain/article/service/ArticleService.java
  src/main/java/com/api/trip/domain/articlefile/service/ArticleFileService.java
  src/main/java/com/api/trip/domain/articlefile/uploader/ArticleFileUploader.java
  src/main/java/com/api/trip/domain/comment/controller/dto/CreateCommentRequest.java
  src/main/java/com/api/trip/domain/comment/service/CommentService.java
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/interestarticle/controller/dto/CreateInterestArticleRequest.java
  src/main/java/com/api/trip/domain/interestarticle/repository/InterestArticleRepository.java
  src/main/java/com/api/trip/domain/interestarticle/service/InterestArticleService.java
  src/main/java/com/api/trip/domain/interestitem/controller/dto/GetInterestItemsResponse.java
  src/main/java/com/api/trip/domain/item/controller/ItemController.java
  src/main/java/com/api/trip/domain/item/controller/dto/CreateItemRequest.java
  src/main/java/com/api/trip/domain/item/controller/dto/GetItemsResponse.java
  src/main/java/com/api/trip/domain/item/model/Item.java
  src/main/java/com/api/trip/domain/item/service/ItemService.java
  src/main/java/com/api/trip/domain/itemtag/repository/ItemTagRepositoryCustom.java
  src/main/java/com/api/trip/domain/itemtag/repository/ItemTagRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/itemtag/service/ItemTagService.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/JoinRequest.java
  src/main/java/com/api/trip/domain/member/controller/dto/LoginRequest.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
  src/main/java/com/api/trip/domain/tag/repository/TagRepository.java
  src/main/java/com/api/trip/domain/tag/service/TagService.java
  src/main/resources/templates/email_auth_mail.html
  src/main/resources/templates/find_password_mail.html
Labels: BugFix, Feat

#114 OAuthSuccessHandler 버그 수정
  src/main/java/com/api/trip/common/security/oauth/OAuth2Attribute.java
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
Labels: BugFix, Feat

#119 Notification 테이블이 생성되지 않는 문제 해결
  src/main/java/com/api/trip/domain/notification/domain/Notification.java
Labels: BugFix

#121 네이버 쇼핑 API 기본 세팅 및 테스트
  src/main/java/com/api/trip/common/init/InitData.java
  src/main/java/com/api/trip/common/naverclient/NaverClient.java
  src/main/java/com/api/trip/common/naverclient/dto/ShoppingItem.java
  src/main/java/com/api/trip/common/naverclient/dto/ShoppingRequest.java
  src/main/java/com/api/trip/common/naverclient/dto/ShoppingResponse.java
Labels: Feat

#123 filter단 예외 처리
  src/main/java/com/api/trip/common/security/jwt/JwtTokenFilter.java
Labels: Feat, Refactor

#125 여행상품 카테고리 분류 및 태그 지정 로직 작성
  src/main/java/com/api/trip/common/init/InitData.java
  src/main/java/com/api/trip/common/naverapi/NaverApiService.java
  src/main/java/com/api/trip/common/naverapi/NaverClient.java
  src/main/java/com/api/trip/common/naverapi/dto/ShoppingItem.java
  src/main/java/com/api/trip/common/naverapi/dto/ShoppingRequest.java
  src/main/java/com/api/trip/common/naverapi/dto/ShoppingResponse.java
  src/main/java/com/api/trip/domain/item/controller/dto/CreateItemRequest.java
Labels: Feat

#130 회원 정보 수정 기능 구현
  src/main/java/com/api/trip/common/exception/ErrorCode.java
  src/main/java/com/api/trip/common/exception/custom_exception/AwsS3Exception.java
  src/main/java/com/api/trip/domain/aws/service/AmazonS3Service.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/UpdateProfileRequest.java
  src/main/java/com/api/trip/domain/member/model/Member.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat

#133 게시판 관련 유효성 검증
  src/main/java/com/api/trip/domain/article/controller/ArticleController.java
  src/main/java/com/api/trip/domain/article/controller/dto/CreateArticleRequest.java
  src/main/java/com/api/trip/domain/article/controller/dto/UpdateArticleRequest.java
  src/main/java/com/api/trip/domain/comment/controller/CommentController.java
  src/main/java/com/api/trip/domain/comment/controller/dto/CreateCommentRequest.java
  src/main/java/com/api/trip/domain/comment/controller/dto/UpdateCommentRequest.java
  src/main/java/com/api/trip/domain/interestarticle/controller/InterestArticleController.java
  src/main/java/com/api/trip/domain/interestarticle/controller/dto/CreateInterestArticleRequest.java
Labels: Feat

#136 [리팩토링] 회원 기능 관련 코드 정리 & 수정
  src/main/java/com/api/trip/common/init/DevInitMember.java
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/member/controller/dto/LoginResponse.java
  src/main/java/com/api/trip/domain/member/model/Member.java
  src/main/java/com/api/trip/domain/member/model/SocialCode.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat, Refactor

#138 관심 태그 설정 기능 구현
  src/main/java/com/api/trip/domain/interesttag/model/InterestTag.java
  src/main/java/com/api/trip/domain/interesttag/respository/InterestTagRepository.java
  src/main/java/com/api/trip/domain/interesttag/service/InterestTagService.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat

#140 마이페이지 기능 구현
  src/main/java/com/api/trip/common/init/DevInitData.java
  src/main/java/com/api/trip/common/init/DevInitMember.java
  src/main/java/com/api/trip/domain/article/repository/ArticleRepository.java
  src/main/java/com/api/trip/domain/comment/repository/CommentRepository.java
  src/main/java/com/api/trip/domain/interestitem/repository/InterestItemRepository.java
  src/main/java/com/api/trip/domain/interesttag/respository/InterestTagRepository.java
  src/main/java/com/api/trip/domain/interesttag/respository/InterestTagRepositoryCustom.java
  src/main/java/com/api/trip/domain/interesttag/respository/InterestTagRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/interesttag/service/InterestTagService.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/MyPageResponse.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat

#141 상품 엔티티 속성 값 데이터 타입 수정
  src/main/java/com/api/trip/common/init/InitData.java
  src/main/java/com/api/trip/domain/item/model/Item.java
Labels: BugFix, Refactor

#142 여행상품 갱신 로직 작성
  src/main/java/com/api/trip/common/init/InitData.java
  src/main/java/com/api/trip/common/schedulerRunner.java
Labels: Feat

#144 소셜 회원 탈퇴 기능 구현
  src/main/java/com/api/trip/common/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/api/trip/common/security/oauth/OAuth2Attribute.java
  src/main/java/com/api/trip/common/security/oauth/OAuth2Revoke.java
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/model/Member.java
  src/main/java/com/api/trip/domain/member/model/SocialCode.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat

#145 12.28 main merge
  src/main/java/com/api/trip/common/init/DevInitData.java
  src/main/java/com/api/trip/common/init/InitData.java
  src/main/java/com/api/trip/common/schedulerRunner.java
  src/main/java/com/api/trip/common/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/api/trip/common/security/oauth/OAuth2Attribute.java
  src/main/java/com/api/trip/common/security/oauth/OAuth2Revoke.java
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/trip/domain/article/repository/ArticleRepository.java
  src/main/java/com/api/trip/domain/comment/repository/CommentRepository.java
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/interestitem/repository/InterestItemRepository.java
  src/main/java/com/api/trip/domain/interesttag/model/InterestTag.java
  src/main/java/com/api/trip/domain/interesttag/respository/InterestTagRepository.java
  src/main/java/com/api/trip/domain/interesttag/respository/InterestTagRepositoryCustom.java
  src/main/java/com/api/trip/domain/interesttag/respository/InterestTagRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/interesttag/service/InterestTagService.java
  src/main/java/com/api/trip/domain/item/model/Item.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/LoginResponse.java
  src/main/java/com/api/trip/domain/member/controller/dto/MyPageResponse.java
  src/main/java/com/api/trip/domain/member/model/Member.java
  src/main/java/com/api/trip/domain/member/model/SocialCode.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat

#146 내가 좋아한 게시글 기능 구현
  src/main/java/com/api/trip/domain/interestarticle/controller/InterestArticleController.java
  src/main/java/com/api/trip/domain/interestarticle/controller/dto/GetMyInterestArticlesResponse.java
  src/main/java/com/api/trip/domain/interestarticle/repository/InterestArticleRepository.java
  src/main/java/com/api/trip/domain/interestarticle/service/InterestArticleService.java
Labels: Feat

#148 여행상품 갱신 로직 수정
  src/main/java/com/api/trip/common/init/InitData.java
  src/main/java/com/api/trip/common/schedulerRunner.java
Labels: Refactor

#151 태그 등록
  src/main/java/com/api/trip/common/init/InitData.java
  src/main/java/com/api/trip/common/scheduler/SchedulerRunner.java
Labels: Feat

#154 알림 기능 구현
  src/main/java/com/api/trip/common/scheduler/SchedulerRunner.java
  src/main/java/com/api/trip/common/sse/SseNotificationResponse.java
  src/main/java/com/api/trip/common/sse/emitter/SseEmitterMap.java
  src/main/java/com/api/trip/domain/interesttag/respository/InterestTagRepositoryCustom.java
  src/main/java/com/api/trip/domain/interesttag/respository/InterestTagRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/interesttag/service/InterestTagService.java
  src/main/java/com/api/trip/domain/item/service/ItemService.java
  src/main/java/com/api/trip/domain/notification/controller/NotificationController.java
  src/main/java/com/api/trip/domain/notification/service/NotificationService.java
Labels: Feat

#157 소셜 로그인 기능 수정
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
Labels: Refactor

#158 main merge
  src/main/java/com/api/trip/common/scheduler/SchedulerRunner.java
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/trip/common/sse/SseNotificationResponse.java
  src/main/java/com/api/trip/common/sse/emitter/SseEmitterMap.java
  src/main/java/com/api/trip/domain/interesttag/respository/InterestTagRepositoryCustom.java
  src/main/java/com/api/trip/domain/interesttag/respository/InterestTagRepositoryCustomImpl.java
  src/main/java/com/api/trip/domain/interesttag/service/InterestTagService.java
  src/main/java/com/api/trip/domain/item/service/ItemService.java
  src/main/java/com/api/trip/domain/notification/controller/NotificationController.java
  src/main/java/com/api/trip/domain/notification/service/NotificationService.java
Labels: Feat, Refactor

#161 여행상품 컨트롤러 버그수정
  src/main/java/com/api/trip/domain/item/controller/ItemController.java
Labels: BugFix

#163 swagger 문서 정리
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
Labels: Docs

#166 여행상품 응답 작성자 제거
  src/main/java/com/api/trip/domain/item/controller/dto/GetItemResponse.java
  src/main/java/com/api/trip/domain/item/repository/ItemRepositoryCustomImpl.java
Labels: BugFix, Refactor

#169 여행상품 api 버그수정
  src/main/java/com/api/trip/domain/item/controller/ItemController.java
  src/main/java/com/api/trip/domain/item/controller/dto/GetItemResponse.java
Labels: BugFix

#172 알림 관련 API 변경
  src/main/java/com/api/trip/domain/notification/controller/NotificationController.java
  src/main/java/com/api/trip/domain/notification/controller/dto/DeleteNotificationRequest.java
  src/main/java/com/api/trip/domain/notification/controller/dto/ReadNotificationRequest.java
  src/main/java/com/api/trip/domain/notification/repository/NotificationRepository.java
  src/main/java/com/api/trip/domain/notification/service/NotificationService.java
  src/main/resources/static/index.html
  src/main/resources/static/src/eventsource.js
Labels: Feat
