Repository TRIP-Side-Project/backend, pull requests merged in 2024-01, with the labels that each got.

#176 태그 추출 키워드 업데이트
  src/main/java/com/api/trip/common/init/InitData.java
  src/main/java/com/api/trip/common/naverapi/NaverApiService.java
Labels: Refactor

#181 List관련 버그수정
  src/main/java/com/api/trip/common/naverapi/NaverApiService.java
Labels: BugFix

#184 관심 상품 API스펙 변경
  src/main/java/com/api/trip/domain/interestitem/controller/InterestItemController.java
  src/main/java/com/api/trip/domain/interestitem/controller/dto/GetInterestItemResponse.java
  src/main/java/com/api/trip/domain/interestitem/controller/dto/GetInterestItemsResponse.java
  src/main/java/com/api/trip/domain/interestitem/service/InterestItemService.java
Labels: Refactor

#185 [고도화] 이메일 인증 기능에 Redis 적용
  src/main/java/com/api/trip/common/exception/ErrorCode.java
  src/main/java/com/api/trip/domain/email/repository/EmailRedisRepository.java
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/EmailResponse.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat, Refactor

#186 소셜 로그인 리다이렉트 url 변경
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
Labels: Feat

#187 네이버 API 버그 및 회원 기능 수정에 의한 Main Merge
  src/main/java/com/api/trip/common/exception/ErrorCode.java
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/trip/domain/email/repository/EmailRedisRepository.java
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/interestitem/controller/InterestItemController.java
  src/main/java/com/api/trip/domain/interestitem/controller/dto/GetInterestItemResponse.java
  src/main/java/com/api/trip/domain/interestitem/controller/dto/GetInterestItemsResponse.java
  src/main/java/com/api/trip/domain/interestitem/service/InterestItemService.java
  src/main/java/com/api/trip/domain/member/controller/MemberController.java
  src/main/java/com/api/trip/domain/member/controller/dto/EmailResponse.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: BugFix, Feat, Refactor

#189 [리팩토링 ]소셜 로그인
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/member/model/Member.java
  src/main/java/com/api/trip/domain/member/repository/MemberRepository.java
Labels: Feat, Refactor

#191 마이페이지 응답 데이터 추가
  src/main/java/com/api/trip/domain/interestarticle/repository/InterestArticleRepository.java
  src/main/java/com/api/trip/domain/member/controller/dto/MyPageResponse.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat, Refactor

#192 회원 기능 수정으로 인한 Main Merge
  src/main/java/com/api/trip/common/security/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/trip/domain/email/service/EmailService.java
  src/main/java/com/api/trip/domain/interestarticle/repository/InterestArticleRepository.java
  src/main/java/com/api/trip/domain/member/controller/dto/MyPageResponse.java
  src/main/java/com/api/trip/domain/member/model/Member.java
  src/main/java/com/api/trip/domain/member/repository/MemberRepository.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat, Refactor

#193 InitData 삭제 Main merge
  src/main/java/com/api/trip/common/init/InitData.java
Labels: BugFix

#197 Refactor: SSE 알림 리팩토링
  src/main/java/com/api/trip/common/scheduler/SchedulerRunner.java
  src/main/java/com/api/trip/common/sse/emitter/SseEmitterMap.java
  src/main/java/com/api/trip/domain/interesttag/service/InterestTagService.java
  src/main/java/com/api/trip/domain/notification/controller/NotificationController.java
  src/main/java/com/api/trip/domain/notification/service/NotificationService.java
Labels: Refactor

#201 관심 태그 기능 수정
  src/main/java/com/api/trip/common/exception/ErrorCode.java
  src/main/java/com/api/trip/common/init/DevInitData.java
  src/main/java/com/api/trip/common/init/InitData.java
  src/main/java/com/api/trip/domain/interesttag/respository/InterestTagRepository.java
  src/main/java/com/api/trip/domain/interesttag/service/InterestTagService.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat, Refactor

#202 관심 태그 기능 리팩토링
  src/main/java/com/api/trip/common/exception/ErrorCode.java
  src/main/java/com/api/trip/common/init/DevInitData.java
  src/main/java/com/api/trip/common/init/InitData.java
  src/main/java/com/api/trip/domain/interesttag/respository/InterestTagRepository.java
  src/main/java/com/api/trip/domain/interesttag/service/InterestTagService.java
  src/main/java/com/api/trip/domain/member/service/MemberService.java
Labels: Feat, Refactor
